const wordList = [
    // A-B
    { eng: "add", heb: "להוסיף", icon: "➕" },
    { eng: "afraid", heb: "מפחד/חושש", icon: "😨" },
    { eng: "alligator", heb: "תנין", icon: "🐊" },
    { eng: "and", heb: "ו-", icon: "🔗" },
    { eng: "ant", heb: "נמלה", icon: "🐜" },
    { eng: "apple", heb: "תפוח", icon: "🍎" },
    { eng: "arm", heb: "זרוע", icon: "💪" },
    { eng: "as", heb: "כפי ש", icon: "🔄" },
    { eng: "ask", heb: "לשאול", icon: "❓" },
    { eng: "at", heb: "ב-", icon: "📍" },
    { eng: "baby", heb: "תינוק", icon: "👶" },
    { eng: "bad", heb: "רע", icon: "👎" },
    { eng: "bag", heb: "תיק", icon: "🎒" },
    { eng: "ball", heb: "כדור", icon: "⚽" },
    { eng: "balloon", heb: "בלון", icon: "🎈" },
    { eng: "banana", heb: "בננה", icon: "🍌" },
    { eng: "bat", heb: "עטלף", icon: "🦇" },
    { eng: "bathroom", heb: "חדר אמבטיה", icon: "🛁" },
    { eng: "bed", heb: "מיטה", icon: "🛏️" },
    { eng: "bedroom", heb: "חדר שינה", icon: "💤" },
    { eng: "best", heb: "הכי טוב", icon: "🏆" },
    { eng: "big", heb: "גדול", icon: "🐘" },
    { eng: "bit", heb: "קצת", icon: "🤏" },
    { eng: "black", heb: "שחור", icon: "⬛" },
    { eng: "blue", heb: "כחול", icon: "🟦" },
    { eng: "book", heb: "ספר", icon: "📖" },
    { eng: "both", heb: "שניהם", icon: "👥" },
    { eng: "box", heb: "קופסה", icon: "📦" },
    { eng: "boy", heb: "בן/ילד", icon: "👦" },
    { eng: "bread", heb: "לחם", icon: "🍞" },
    { eng: "brother", heb: "אח", icon: "👦" },
    { eng: "brown", heb: "חום", icon: "🟤" },
    { eng: "bus", heb: "אוטובוס", icon: "🚌" },
    { eng: "but", heb: "אבל", icon: "✋" },
    // C-D
    { eng: "cake", heb: "עוגה", icon: "🎂" },
    { eng: "camp", heb: "מחנה", icon: "⛺" },
    { eng: "can", heb: "יכול", icon: "✅" },
    { eng: "cat", heb: "חתול", icon: "🐱" },
    { eng: "chair", heb: "כיסא", icon: "🪑" },
    { eng: "classroom", heb: "כיתה", icon: "🏫" },
    { eng: "clouds", heb: "עננים", icon: "☁️" },
    { eng: "clown", heb: "ליצן", icon: "🤡" },
    { eng: "cold", heb: "קר", icon: "❄️" },
    { eng: "crayons", heb: "צבעים", icon: "🖍️" },
    { eng: "cut", heb: "לגזור", icon: "✂️" },
    { eng: "dad", heb: "אבא", icon: "👨" },
    { eng: "desk", heb: "שולחן כתיבה", icon: "📑" },
    { eng: "did", heb: "עשה", icon: "✔️" },
    { eng: "didn't", heb: "לא עשה", icon: "✖️" },
    { eng: "do", heb: "עושה", icon: "⚙️" },
    { eng: "doctor", heb: "רופא", icon: "👨‍⚕️" },
    { eng: "dog", heb: "כלב", icon: "🐶" },
    { eng: "door", heb: "דלת", icon: "🚪" },
    { eng: "duck", heb: "ברווז", icon: "🦆" },
    // E-F
    { eng: "ears", heb: "אוזניים", icon: "👂" },
    { eng: "egg", heb: "ביצה", icon: "🥚" },
    { eng: "eight", heb: "שמונה", icon: "8️⃣" },
    { eng: "elephant", heb: "פיל", icon: "🐘" },
    { eng: "end", heb: "סוף", icon: "🏁" },
    { eng: "eyes", heb: "עיניים", icon: "👀" },
    { eng: "face", heb: "פנים", icon: "👤" },
    { eng: "fall", heb: "סתיו", icon: "🍂" },
    { eng: "fall off", heb: "ליפול מ...", icon: "📉" },
    { eng: "family", heb: "משפחה", icon: "👨‍👩‍👧‍👦" },
    { eng: "fan", heb: "מאוורר", icon: "🌀" },
    { eng: "farm", heb: "חווה", icon: "🚜" },
    { eng: "fast", heb: "מהר", icon: "⚡" },
    { eng: "fat", heb: "שמן", icon: "🍔" },
    { eng: "father", heb: "אבא", icon: "🧔" },
    { eng: "feet", heb: "כפות רגליים", icon: "👣" },
    { eng: "five", heb: "חמש", icon: "5️⃣" },
    { eng: "flour", heb: "קמח", icon: "🌾" },
    { eng: "four", heb: "ארבע", icon: "4️⃣" },
    { eng: "friend", heb: "חבר", icon: "🤝" },
    { eng: "from", heb: "מ -", icon: "⬅️" },
    { eng: "fun", heb: "כיף", icon: "🥳" },
    // G-H
    { eng: "get", heb: "לקבל", icon: "🎁" },
    { eng: "gift", heb: "מתנה", icon: "🎀" },
    { eng: "girl", heb: "בת/ילדה", icon: "👧" },
    { eng: "glue", heb: "דבק", icon: "🧪" },
    { eng: "go", heb: "ללכת", icon: "🚶" },
    { eng: "gorilla", heb: "גורילה", icon: "🦍" },
    { eng: "green", heb: "ירוק", icon: "🟩" },
    { eng: "guitar", heb: "גיטרה", icon: "🎸" },
    { eng: "had", heb: "היה", icon: "⏳" },
    { eng: "hair", heb: "שיער", icon: "💇" },
    { eng: "hand", heb: "יד", icon: "🖐️" },
    { eng: "happy", heb: "שמח", icon: "😊" },
    { eng: "has", heb: "יש לו / לה", icon: "👜" },
    { eng: "hat", heb: "כובע", icon: "🎩" },
    { eng: "he", heb: "הוא", icon: "👨" },
    { eng: "help", heb: "לעזור", icon: "🆘" },
    { eng: "hen", heb: "תרנגולת", icon: "🐔" },
    { eng: "him", heb: "אותו", icon: "👉" },
    { eng: "his", heb: "שלו", icon: "👦" },
    { eng: "hit", heb: "מכה", icon: "🔨" },
    { eng: "hot", heb: "חם", icon: "🔥" },
    { eng: "house", heb: "בית", icon: "🏠" },
    // I-K
    { eng: "I", heb: "אני", icon: "🙋" },
    { eng: "if", heb: "אם", icon: "💡" },
    { eng: "igloo", heb: "איגלו", icon: "🧊" },
    { eng: "in", heb: "בתוך", icon: "📥" },
    { eng: "Internet", heb: "אינטרנט", icon: "🌐" },
    { eng: "jacket", heb: "ז'קט / מעיל", icon: "🧥" },
    { eng: "job", heb: "עבודה", icon: "💼" },
    { eng: "jump", heb: "לקפוץ", icon: "🛘" },
    { eng: "kangaroo", heb: "קנגורו", icon: "🦘" },
    { eng: "kids", heb: "ילדים", icon: "🧒" },
    { eng: "king", heb: "מלך", icon: "👑" },
    { eng: "kitchen", heb: "מטבח", icon: "🍳" },
    // L-M
    { eng: "last", heb: "אחרון", icon: "🔚" },
    { eng: "left", heb: "שמאלה", icon: "⬅️" },
    { eng: "leg/s", heb: "רגל/רגליים", icon: "🦵" },
    { eng: "lemon", heb: "לימון", icon: "🍋" },
    { eng: "let", heb: "לאפשר", icon: "🔓" },
    { eng: "library", heb: "ספרייה", icon: "📚" },
    { eng: "lion", heb: "אריה", icon: "🦁" },
    { eng: "list", heb: "רשימה", icon: "📜" },
    { eng: "listen", heb: "להקשיב", icon: "👂" },
    { eng: "living room", heb: "סלון", icon: "🛋️" },
    { eng: "long", heb: "ארוך", icon: "📏" },
    { eng: "lost", heb: "אבוד", icon: "🔍" },
    { eng: "man", heb: "איש", icon: "👨" },
    { eng: "mat", heb: "שטיח", icon: "🧶" },
    { eng: "me", heb: "לי", icon: "🙋‍♂️" },
    { eng: "men", heb: "גברים/אנשים", icon: "👥" },
    { eng: "milk", heb: "חלב", icon: "🥛" },
    { eng: "mix", heb: "לערבב", icon: "🥣" },
    { eng: "mom", heb: "אמא", icon: "👩" },
    { eng: "monkey", heb: "קוף", icon: "🐒" },
    { eng: "mother", heb: "אמא", icon: "🤱" },
    { eng: "mouth", heb: "פה", icon: "👄" },
    // N-P
    { eng: "near", heb: "ליד", icon: "📏" },
    { eng: "net", heb: "רשת", icon: "🕸️" },
    { eng: "next (to)", heb: "ליד", icon: "⏭️" },
    { eng: "nine", heb: "תשע", icon: "9️⃣" },
    { eng: "no", heb: "לא", icon: "❌" },
    { eng: "nose", heb: "אף", icon: "👃" },
    { eng: "not", heb: "לא", icon: "🚫" },
    { eng: "on", heb: "מעל", icon: "🔛" },
    { eng: "one", heb: "אחד", icon: "1️⃣" },
    { eng: "open", heb: "לפתוח", icon: "📖" },
    { eng: "orange", heb: "כתום", icon: "🟠" },
    { eng: "pan", heb: "מחבת", icon: "🍳" },
    { eng: "paper", heb: "נייר", icon: "📄" },
    { eng: "pen", heb: "עט", icon: "🖊️" },
    { eng: "pencil", heb: "עיפרון", icon: "✏️" },
    { eng: "pet", heb: "חיית מחמד", icon: "🐾" },
    { eng: "pink", heb: "ורוד", icon: "🩷" },
    { eng: "pizza", heb: "פיצה", icon: "🍕" },
    { eng: "plan", heb: "תוכנית / תרשים", icon: "🗺️" },
    { eng: "play", heb: "לשחק", icon: "🎮" },
    { eng: "poster", heb: "פוסטר", icon: "🖼️" },
    { eng: "pupil", heb: "תלמיד", icon: "🧑‍🎓" },
    { eng: "purple", heb: "סגול", icon: "🟣" },
    // Q-S
    { eng: "queen", heb: "מלכה", icon: "👸" },
    { eng: "question", heb: "שאלה", icon: "❓" },
    { eng: "quiet", heb: "שקט", icon: "🤫" },
    { eng: "rain", heb: "גשם", icon: "🌧️" },
    { eng: "read", heb: "לקרוא", icon: "📖" },
    { eng: "red", heb: "אדום", icon: "🔴" },
    { eng: "rest", heb: "לנוח", icon: "🛌" },
    { eng: "right", heb: "ימינה", icon: "➡️" },
    { eng: "roof", heb: "גג", icon: "🏠" },
    { eng: "ruler", heb: "סרגל", icon: "📏" },
    { eng: "run", heb: "לרוץ", icon: "🏃" },
    { eng: "sad", heb: "עצוב", icon: "😢" },
    { eng: "scarf", heb: "צעיף", icon: "🧣" },
    { eng: "school", heb: "בית ספר", icon: "🏫" },
    { eng: "scissors", heb: "מספריים", icon: "✂️" },
    { eng: "self", heb: "אני / עצמי", icon: "🆔" },
    { eng: "seven", heb: "שבע", icon: "7️⃣" },
    { eng: "she", heb: "היא", icon: "👧" },
    { eng: "sister", heb: "אחות", icon: "👭" },
    { eng: "sit (down)", heb: "שב/שבי", icon: "🪑" },
    { eng: "six", heb: "שש", icon: "6️⃣" },
    { eng: "sky", heb: "שמיים", icon: "🌤️" },
    { eng: "small", heb: "קטן", icon: "🐭" },
    { eng: "snake", heb: "נחש", icon: "🐍" },
    { eng: "so", heb: "כך / לכן", icon: "👉" },
    { eng: "soft", heb: "רך", icon: "🧸" },
    { eng: "spring", heb: "אביב", icon: "🌸" },
    { eng: "stand (up)", heb: "עמוד/עמדי", icon: "🚶‍♂️" },
    { eng: "star", heb: "כוכב", icon: "⭐" },
    { eng: "stop", heb: "עצור", icon: "🛑" },
    { eng: "strong", heb: "חזק", icon: "💪" },
    { eng: "summer", heb: "קיץ", icon: "☀️" },
    { eng: "sun", heb: "שמש", icon: "🌞" },
    { eng: "surprised", heb: "מופתע", icon: "😲" },
    { eng: "swim", heb: "לשחות", icon: "🏊" },
    // T-Z
    { eng: "tail", heb: "זנב", icon: "🐕‍🦺" },
    { eng: "talk", heb: "לדבר", icon: "🗣️" },
    { eng: "tall", heb: "גבוה", icon: "🦒" },
    { eng: "teacher", heb: "מורה", icon: "👩‍🏫" },
    { eng: "television", heb: "טלוויזיה", icon: "📺" },
    { eng: "ten", heb: "עשר", icon: "🔟" },
    { eng: "test", heb: "מבחן", icon: "📝" },
    { eng: "there", heb: "שם", icon: "📍" },
    { eng: "this", heb: "זה", icon: "👈" },
    { eng: "three", heb: "שלוש", icon: "3️⃣" },
    { eng: "to", heb: "ל-", icon: "➡️" },
    { eng: "top", heb: "ראש / פסגה", icon: "🏔️" },
    { eng: "tree", heb: "עץ", icon: "🌳" },
    { eng: "two", heb: "שתיים", icon: "2️⃣" },
    { eng: "umbrella", heb: "מטרייה", icon: "☂️" },
    { eng: "under", heb: "מתחת", icon: "👇" },
    { eng: "up", heb: "למעלה", icon: "🆙" },
    { eng: "us", heb: "אנחנו", icon: "👨‍👩‍👦" },
    { eng: "van", heb: "טנדר", icon: "🚐" },
    { eng: "vet", heb: "וטרינר", icon: "🩺" },
    { eng: "video", heb: "וידאו", icon: "🎬" },
    { eng: "walk", heb: "ללכת", icon: "🚶‍♀️" },
    { eng: "wet", heb: "רטוב", icon: "💧" },
    { eng: "wheat", heb: "חיטה", icon: "🌾" },
    { eng: "white", heb: "לבן", icon: "⬜" },
    { eng: "wind", heb: "רוח", icon: "🌬️" },
    { eng: "window", heb: "חלון", icon: "🪟" },
    { eng: "winter", heb: "חורף", icon: "❄️" },
    { eng: "woman", heb: "אישה", icon: "👩" },
    { eng: "yard", heb: "חצר", icon: "🏡" },
    { eng: "yellow", heb: "צהוב", icon: "🟡" },
    { eng: "yes", heb: "כן", icon: "✅" },
    { eng: "you", heb: "את/ה", icon: "🫵" },
    { eng: "zebra", heb: "זברה", icon: "🦓" },
    { eng: "zero", heb: "אפס", icon: "0️⃣" },
    { eng: "zoo", heb: "גן חיות", icon: "🦒" }
];